--- 
addons: 
  apt: 
    packages: 
      - salt-common
      - salt-master

    sources: 
      - 
        sourceline: "deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main"
      - 
        key_url: "https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub"
before_script: "salt --version"
dist: trusty
install: 
  - "export PATH=$PATH:$PWD/usr/bin/"
language: go
script: 
  - "bash .ci-travis/terraform-validation"
  - "bash .ci-travis/salt-server-validation"
  - "bash .ci-travis/salt-client-validation"
  - "bash .ci-travis/salt-minion-validation"
  - "bash .ci-travis/salt-ctl-validation"
sudo: false

